[package]
name = "spillestation"
version = "0.1.0"
edition = "2021"
resolver = "2"

[profile.dev]
opt-level = 3

[dependencies]
splst_front = { path = "crates/splst_front" }
splst_core = { path = "crates/splst_core" }
env_logger = "*"
log = "*"
